# Generated by Django 4.2 on 2023-04-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('inventory_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryledger',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_ledgers', to='item.item'),
        ),
    ]
