# Generated by Django 4.2 on 2023-04-12 12:59

from django.db import migrations, models
import django.db.models.deletion
import item_image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_model_specification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=item_image.models.item_image_directory_path)),
                ('item_model_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item_model_specification.itemmodelspecification')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
