# Generated by Django 4.2 on 2023-04-13 13:38

from django.db import migrations, models
import merchant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=merchant.models.merchant_directory_path)),
                ('partners', models.ManyToManyField(blank=True, related_name='merchants', to='partner.partner')),
            ],
        ),
    ]
