# Generated by Django 4.2 on 2023-04-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='merchants',
            field=models.ManyToManyField(related_name='warehouses', to='merchant.merchant'),
        ),
    ]
