# Generated by Django 4.2 on 2023-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_variant_specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariantspecification',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], max_length=50, null=True),
        ),
    ]
