# Generated by Django 4.2 on 2023-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_model_specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodelspecification',
            name='brand_collection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodelspecification',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodelspecification',
            name='care_instructions',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodelspecification',
            name='color',
            field=models.CharField(blank=True, choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Green', 'Green'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('White', 'White')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodelspecification',
            name='description_long',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodelspecification',
            name='description_short',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodelspecification',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
