# Generated by Django 4.2 on 2023-04-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariantspecification',
            name='valid_from',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemvariantspecification',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
