name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI_PIPELINE_ID: ${{ github.run_id }}
  CI_COMMIT_REF_NAME: ${{ github.ref }}

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Pull
        run: docker pull "${{ secrets.CI_REGISTRY_IMAGE }}:latest"
        continue-on-error: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: docker build --tag="${{ github.run_id }}:${{ github.ref }}" --cache-from="${{ secrets.CI_REGISTRY_IMAGE }}:latest" .

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "CI_PIPELINE_ID=${{ github.run_id }}" >> $GITHUB_ENV
          echo "CI_BUILD_REF_NAME=${{ github.ref }}" >> $GITHUB_ENV
      - name: Lint
        run: |
          docker compose -p "${{ github.run_id }}" -f docker-compose.ci.yml run backend flake8 .

  push-main:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Docker Tag and Push (Main)
        run: |
          docker tag "${{ github.run_id }}:${{ github.ref }}" "${{ secrets.CI_REGISTRY_IMAGE }}:${{ github.ref }}"
          docker push "${{ secrets.CI_REGISTRY_IMAGE }}:${{ github.ref }}"

  push-latest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker Tag and Push (Latest)
        run: |
          docker tag "${{ github.run_id }}:${{ github.ref }}" "${{ secrets.CI_REGISTRY_IMAGE }}:latest"
          docker push "${{ secrets.CI_REGISTRY_IMAGE }}:latest"

  cleanup:
    runs-on: ubuntu-latest
    needs: [push-main, push-latest]
    always: true
    steps:
      - name: Cleanup
        run: |
          docker rmi -f "${{ github.run_id }}:${{ github.ref }}"
          docker compose -p "${{ github.run_id }}" -f docker-compose.ci.yml down --remove-orphans

  deploy:
    needs: cleanup
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          docker compose -f docker-compose.deploy.yml pull
          docker compose -f docker-compose.deploy.yml down --remove-orphans
          docker volume rm erp-system_build
          docker compose -f docker-compose.deploy.yml up -d